### ISSUE TITLE
Description Need Correction

### ISSUE THREAD

**Issue by eagleanurag** [kornicameister/gh-secrets-action#64]
❌THIS REPOSITORY DOES NOT ANYTHING THAT IT SHOULD NOT DO. IT WILL CREATE OR UPDATE SECRETS IN DESIGNATED REPISOTORY AND STOP AT IT.❌

✅THIS REPOSITORY DOES NOT DO ANYTHING THAT IT SHOULD NOT DO. IT WILL CREATE OR UPDATE SECRETS IN DESIGNATED REPISOTORY AND STOP AT IT.✅

**Comment by kornicameister** [comment]
@eagleanurag you'd like to get red crosses? Is that correct?
I think that makes sense, it will be catchy :)

**Comment by eagleanurag** [comment]
Ops!   

ok from next time there will be no red crosses!

> 
> 
> @eagleanurag you'd like to get red crosses? Is that correct?
> I think that makes sense, it will be catchy :)
> 
> Care to drop another PR?

Ops!   

ok from next time there will be no red crosses!
